
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrvaska
resources:
  - solr.yaml
  - api.yaml
images:
  -
    name: parlasearch
    newName: rg.fr-par.scw.cloud/djnd/parlasearch
    newTag: '7d71aecea4e97e971622b168b7ad4b3ee25c5b52'
  -
    name: parlasolr
    newName: rg.fr-par.scw.cloud/djnd/parlasolr
    newTag: '7d71aecea4e97e971622b168b7ad4b3ee25c5b52'
