
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrvaska
resources:
  - solr.yaml
images:
  -
    name: parlasearch
    newName: rg.fr-par.scw.cloud/djnd/parlasearch
    newTag: '2af831187773319ae3f300a53166d3c018f637b2'
  -
    name: parlasolr
    newName: rg.fr-par.scw.cloud/djnd/parlasolr
    newTag: '2af831187773319ae3f300a53166d3c018f637b2'
