
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter
resources:
  - solr.yaml
images:
  - name: parlasolr
    newName: rg.fr-par.scw.cloud/djnd/parlasolr
    newTag: '2f8060380647a9681b688b061f4141568410e809'
