
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrvaska
resources:
  - solr.yaml
images:
  -
    name: parlasearch
    newName: rg.fr-par.scw.cloud/djnd/parlasearch
    newTag: 'a86d86bdd31b59b2e324bdf9f6decfa46fba6668'
  -
    name: parlasolr
    newName: rg.fr-par.scw.cloud/djnd/parlasolr
    newTag: 'a86d86bdd31b59b2e324bdf9f6decfa46fba6668'
