
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter
resources:
  - solr.yaml
images:
  - name: parlasolr
    newName: rg.fr-par.scw.cloud/djnd/parlasolr
    newTag: 'b17ad026bf971b29ccdad402a8484fed5f00caa5'
