
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrvaska
resources:
  - solr.yaml
images:
  -
    name: parlasearch
    newName: rg.fr-par.scw.cloud/djnd/parlasearch
    newTag: 'fcd9a80e0927a1ec70d64c656bf02f40d34b8996'
  -
    name: parlasolr
    newName: rg.fr-par.scw.cloud/djnd/parlasolr
    newTag: 'fcd9a80e0927a1ec70d64c656bf02f40d34b8996'
